export const publicKey = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqdr+OW8+gnEaXl72QwpX
37PHcVeozkhyKbdTVKQ5Ntm2jhWuOOUBpDrGC7Y65XhbPlhVFxUa6/ZswlWYdC9U
S1juI1AlyMBmx8x7ywcSYbLVWHB3utBNTRWgNmbRu63ji2skLC022H/IqAPNCGs6
MeEOBkQGH4gYdKlLeRnRj/QN804vc3uyoCZhmKAmF8AQtoIiuNVUnQrclBHmPYIE
AsBIpaxPp84ccnOZ5B5qngYYEt+mREr7xUrI8xjPDeT7VReej2YpwWIpp/Pbwlcr
cPtZYFM1/otC+z+R9fIRAxltaob4YoqGxXTnuRpwXnbkpfdpvkNA/a9I1tu4qAin
UQIDAQAB
-----END PUBLIC KEY-----
`