export const str = `ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+[]{}|;:,.<>?/~\`😊😂😍🥰😎👍🔥💖'"?/|\\`;

export const json = {
  large: JSON.stringify({
    username: "admin",
    password: "admin",
    role: "admin",
    ip: "127.0.0.1",
    timestamp: Date.now(),
    nonce: Math.random(),
    version: "1.0.0",
    signature: "signature",
    data: "data",
    extra: "extra",
    extra2: "extra2",
    extra3: "extra3",
    extra4: "extra4",
    address: {
      street: "123 Main St",
      city: "Anytown",
      state: "CA",
      zip: "12345",
      country: "USA",
    },
    address2: {
      street: "123 Main St",
      city: "Anytown",
      state: "CA",
      zip: "12345",
      country: "USA",
    },
    users: [
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
      {
        username: "admin",
        password: "admin",
        role: "admin",
        ip: "127.0.0.1",
        timestamp: Date.now(),
        nonce: Math.random(),
        version: "1.0.0",
        signature: "signature",
        data: "data",
        extra: "extra",
        extra2: "extra2",
        extra3: "extra3",
        extra4: "extra4",
        address: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
        address2: {
          street: "123 Main St",
          city: "Anytown",
          state: "CA",
          zip: "12345",
          country: "USA",
        },
      },
    ],
  }),
  mini: JSON.stringify({
    username: "admin",
    password: "admin",
    role: "admin",
    ip: "127.0.0.1",
    timestamp: Date.now(),
    nonce: Math.random(),
    version: "1.0.0",
    signature: "signature",
    data: "data",
    extra: "extra",
    extra2: "extra2",
    extra3: "extra3",
    extra4: "extra4",
    address: {
      street: "123 Main St",
      city: "Anytown",
      state: "CA",
      zip: "12345",
      country: "USA",
    },
  }),
};
